on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: guvenkaranfil/hello-gh-action@v1.6
        with:
          who-to-greet: "Mona the Octocat"

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        env:
          AC_ACCESS_TOKEN: ${{ secrets.AC_ACCESS_TOKEN }}
