on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # Use the output from the `hello` step
      - name: Confirm Secrets
        run: |
          echo "AC_ACCESS_TOKEN is set"
          echo $AC_ACCESS_TOKEN
        env:
          AC_ACCESS_TOKEN: ${{ secrets.AC_ACCESS_TOKEN }}
      - name: Hello world action step
        id: hello
        uses: guvenkaranfil/hello-gh-action@v1.5
        with:
          who-to-greet: "Mona the Octocat"

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
        env:
          AC_ACCESS_TOKEN: ${{ secrets.AC_ACCESS_TOKEN }}
